export const todoConstants = {


    TODO_ADD_REQUEST: 'TODO_ADD_REQUEST',
    TODO_ADD_SUCCESS: 'TODO_ADD_SUCCESS',
    TODO_ADD_FAILURE: 'TODO_ADD_FAILURE',

    GETALL_REQUEST: 'TODO_GETALL_REQUEST',
    GETALL_SUCCESS: 'TODO_GETALL_SUCCESS',
    GETALL_FAILURE: 'TODO_GETALL_FAILURE',

    COMPLETED_REQUEST: 'TODO_COMPLETED_REQUEST',
    COMPLETED_SUCCESS: 'TODO_COMPLETED_SUCCESS',
    COMPLETED_FAILURE: 'TODO_COMPLETED_FAILURE',

    EDIT_REQUEST: 'TODO_EDIT_REQUEST',
    EDIT_SUCCESS: 'TODO_EDIT_SUCCESS',
    EDIT_FAILURE: 'TODO_EDIT_FAILURE',


    DELETE_REQUEST: 'TODO_DELETE_REQUEST',
    DELETE_SUCCESS: 'TODO_DELETE_SUCCESS',
    DELETE_FAILURE: 'TODO_DELETE_FAILURE'

};
